version: '3.9'

services:

  app:
    build:
      context: .
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate &&
              gunicorn app.wsgi --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"


  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
