# Generated by Django 5.0.4 on 2024-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
